version: 2
updates:
  - package-ecosystem: cargo
    directory: /src/rust/compute-service
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      cargo:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /src/rust/mdqc-core
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      cargo:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /src/go/control-plane
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      go_modules:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /src/python
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
