// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.28.2
// source: core_compute.proto

package corepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CoreCompute_CosineSimilarity_FullMethodName = "/mdqc.core.v1.CoreCompute/CosineSimilarity"
)

// CoreComputeClient is the client API for CoreCompute service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreComputeClient interface {
	CosineSimilarity(ctx context.Context, in *CosineSimilarityRequest, opts ...grpc.CallOption) (*CosineSimilarityResponse, error)
}

type coreComputeClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreComputeClient(cc grpc.ClientConnInterface) CoreComputeClient {
	return &coreComputeClient{cc}
}

func (c *coreComputeClient) CosineSimilarity(ctx context.Context, in *CosineSimilarityRequest, opts ...grpc.CallOption) (*CosineSimilarityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CosineSimilarityResponse)
	err := c.cc.Invoke(ctx, CoreCompute_CosineSimilarity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreComputeServer is the server API for CoreCompute service.
// All implementations must embed UnimplementedCoreComputeServer
// for forward compatibility
type CoreComputeServer interface {
	CosineSimilarity(context.Context, *CosineSimilarityRequest) (*CosineSimilarityResponse, error)
	mustEmbedUnimplementedCoreComputeServer()
}

// UnimplementedCoreComputeServer must be embedded to have forward compatible implementations.
type UnimplementedCoreComputeServer struct {
}

func (UnimplementedCoreComputeServer) CosineSimilarity(context.Context, *CosineSimilarityRequest) (*CosineSimilarityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CosineSimilarity not implemented")
}
func (UnimplementedCoreComputeServer) mustEmbedUnimplementedCoreComputeServer() {}

// UnsafeCoreComputeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreComputeServer will
// result in compilation errors.
type UnsafeCoreComputeServer interface {
	mustEmbedUnimplementedCoreComputeServer()
}

func RegisterCoreComputeServer(s grpc.ServiceRegistrar, srv CoreComputeServer) {
	s.RegisterService(&CoreCompute_ServiceDesc, srv)
}

func _CoreCompute_CosineSimilarity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosineSimilarityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreComputeServer).CosineSimilarity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreCompute_CosineSimilarity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreComputeServer).CosineSimilarity(ctx, req.(*CosineSimilarityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreCompute_ServiceDesc is the grpc.ServiceDesc for CoreCompute service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreCompute_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mdqc.core.v1.CoreCompute",
	HandlerType: (*CoreComputeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CosineSimilarity",
			Handler:    _CoreCompute_CosineSimilarity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core_compute.proto",
}
